# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wyliodrin Build

on:
  push:
  pull_request:

jobs:
  build-electron:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: Wyliodrin STUDIO-2.2.0-beta.AppImage
            asset_name: wyliodrinstudio-linux-amd64
          - os: windows-latest
            artifact_name: Wyliodrin STUDIO Setup 2.2.0-beta.exe
            asset_name: wyliodrinstudio-windows-amd64
          - os: macos-latest
            artifact_name: Wyliodrin STUDIO-2.2.0-beta.dmg
            asset_name: wyliodrinstudio-macos-amd64
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          node-version: 12.x
      - run: npm install
      - run: npx electron-rebuild
      - run: npm run dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Wyliodrin STUDIO 2.2.0-beta"