# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Wyliodrin Documentation

on:
  push:
    branches:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
        node-version: 12.x
    - name: Install dependencies
      run: |
        npm install -g jsdoc
        python -m pip install --upgrade pip
        cd docs
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build docs
      run: |
        cd docs/source
        make html
